"""
Django settings for aplicacion_Emprendimiento_Django project.

Generated by 'django-admin startproject' using Django 4.2.25.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # 👈 Carga variables desde el archivo .env

# ========================
# BASE CONFIGURATION
# ========================

BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables del archivo .env
load_dotenv()

# ========================
# SECURITY
# ========================

# 🔒 Clave secreta (mantenla en .env en producción)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-8f6b056dxjkoi_=$^^tcfmnqdl75%+(5g#3c0koj8l#anw4l7j')

# ⚠️ Cambia DEBUG a False cuando publiques tu proyecto
DEBUG = True

ALLOWED_HOSTS = ['*']  # Puedes ajustar esto si despliegas el sitio


# ========================
# APPLICATIONS
# ========================

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tus apps personalizadas
    'general',
    'cursos',
    'dashboard',
]


# ========================
# MIDDLEWARE
# ========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ========================
# URLS & WSGI
# ========================

ROOT_URLCONF = 'aplicacion_Emprendimiento_Django.urls'
WSGI_APPLICATION = 'aplicacion_Emprendimiento_Django.wsgi.application'


# ========================
# TEMPLATES
# ========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 📁 Carpeta global de plantillas
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ========================
# DATABASE
# ========================

# ========================
# PASSWORD VALIDATION
# ========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ========================
# INTERNATIONALIZATION
# ========================

LANGUAGE_CODE = 'es'         # 🇪🇸 cambia idioma del sitio
TIME_ZONE = 'America/Guayaquil'  # ⏰ zona horaria Ecuador
USE_I18N = True
USE_TZ = True


# ========================
# STATIC FILES
# ========================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# ========================
# DEFAULTS
# ========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

X_FRAME_OPTIONS = 'ALLOWALL'
# ========================
# OPENAI API CONFIG
# ========================

# 🔑 Carga tu clave de OpenAI desde el archivo .env
OPENAI_API_KEY = "ac8819c2-ee7a-4b81-8080-fa245705b1f2"
