# Generated by Django 4.2.25 on 2025-12-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_ACTIVIDAD', models.CharField(max_length=255)),
                ('DURACION_TOTAL_ACTIVIDAD', models.DecimalField(decimal_places=2, max_digits=8)),
                ('FECHA_MODIFICACION_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_ACTIVIDAD', models.BooleanField(default=True)),
                ('PUNTUACION_GENERAL_ACTIVIDAD', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ACTXCUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDEN_SECCION_CURSO', models.IntegerField()),
                ('NOMBRE_ACTXCUR', models.CharField(blank=True, max_length=255)),
                ('FECHA_MODIFICACION_ACTXCUR', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_ACTXCUR', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_ACTXCUR', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sección de curso',
                'verbose_name_plural': 'Secciones de curso',
                'ordering': ['ORDEN_SECCION_CURSO'],
            },
        ),
        migrations.CreateModel(
            name='ACTXUSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPLETO_ACTXUSE', models.BooleanField(default=False)),
                ('ESTADO_ACTXUSE', models.BooleanField(default=True)),
                ('FECHA_INGRESO_ACTXUSE', models.DateTimeField(auto_now_add=True)),
                ('FECHA_MODIFICACION_ACTXUSE', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CURSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_CURSO', models.CharField(max_length=255)),
                ('DESCRIPCION_CURSO', models.CharField(max_length=255)),
                ('URL_PORTADA_CURSO', models.CharField(blank=True, max_length=255, null=True)),
                ('PUNTUACION_GENERAL_CURSO', models.DecimalField(decimal_places=2, max_digits=4)),
                ('SUBSCRIPCION_TOTAL_CURSO', models.IntegerField()),
                ('DURACION_TOTAL_CURSO', models.DecimalField(decimal_places=2, max_digits=6)),
                ('COSTO_TOTAL_CURSO', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ITEM_TOTAL_CURSO', models.IntegerField()),
                ('FECHA_MODIFICACION_CURSO', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_CURSO', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_CURSO', models.BooleanField(default=True)),
                ('ESTADO_PUBLICACION_CURSO', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CURXUSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_MODIFICACION_CURXUSE', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_CURXUSE', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_CURXUSE', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso por usuario',
                'verbose_name_plural': 'Cursos por usuario',
            },
        ),
        migrations.CreateModel(
            name='DESCRIPCION_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION_DESCRIPCION_ACTIVIDAD', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION_DESCRIPCION_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_DESCRIPCION_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_DESCRIPCION_ACTIVIDAD', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Descripción de actividad',
                'verbose_name_plural': 'Descripciones de actividad',
            },
        ),
        migrations.CreateModel(
            name='FORO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_FORO', models.CharField(max_length=255)),
                ('DESCRIPCION_FORO', models.CharField(max_length=255)),
                ('FECHA_INGRESO_FORO', models.DateTimeField(auto_now_add=True)),
                ('FECHA_MODIFICACION_FORO', models.DateField(auto_now=True)),
                ('ESTADO_FORO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Foro',
                'verbose_name_plural': 'Foros',
            },
        ),
        migrations.CreateModel(
            name='IMAGEN_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_IMAGEN_ACTIVIDAD', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION_IMAGEN_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_IMAGEN_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_IMAGEN_ACTIVIDAD', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen de actividad',
                'verbose_name_plural': 'Imágenes de actividad',
            },
        ),
        migrations.CreateModel(
            name='OPINION_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION_OPINION_ACTIVIDAD', models.CharField(max_length=255)),
                ('PUNTUACION_OPINION_ACTIVIDAD', models.DecimalField(decimal_places=2, max_digits=4)),
                ('FECHA_MODIFICACION_OPINION_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_OPINION_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_OPINION_ACTIVIDAD', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opinión de actividad',
                'verbose_name_plural': 'Opiniones de actividad',
            },
        ),
        migrations.CreateModel(
            name='TIPO_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_TIPO_ACTIVIDAD', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION_TIPO_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_TIPO_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_TIPO_ACTIVIDAD', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividad',
            },
        ),
        migrations.CreateModel(
            name='VIDEO_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_VIDEO_ACTIVIDAD', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION_VIDEO_ACTIVIDAD', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_VIDEO_ACTIVIDAD', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_VIDEO_ACTIVIDAD', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.actividad')),
            ],
            options={
                'verbose_name': 'Video de actividad',
                'verbose_name_plural': 'Videos de actividad',
            },
        ),
        migrations.CreateModel(
            name='REQUISITO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_REQUISITO', models.CharField(max_length=150)),
                ('FECHA_MODIFICACION_REQUISITO', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_REQUISITO', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_REQUISITO', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='POLITICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_POLITICA', models.CharField(max_length=255)),
                ('DESCRIPCION_POLITICA', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION_POLITICA', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_POLITICA', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_POLITICA', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Politica',
                'verbose_name_plural': 'Politicas',
            },
        ),
        migrations.CreateModel(
            name='PDF_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_PDF_ACTIVIDAD', models.CharField(max_length=255, verbose_name='URL del PDF')),
                ('FECHA_INGRESO_PDF_ACTIVIDAD', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('FECHA_MODIFICACION_PDF_ACTIVIDAD', models.DateField(auto_now=True)),
                ('ESTADO_PDF_ACTIVIDAD', models.BooleanField(default=True, verbose_name='PDF activo')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='cursos.actividad')),
            ],
            options={
                'verbose_name': 'PDF de actividad',
                'verbose_name_plural': 'PDF de actividades',
            },
        ),
        migrations.CreateModel(
            name='OPINION_FORO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_INGRESO_OPINION_FORO', models.DateTimeField(auto_now_add=True)),
                ('FECHA_MODIFICACION_OPINION_FORO', models.DateField(auto_now=True)),
                ('ESTADO_OPINION_FORO', models.BooleanField(default=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='cursos.foro')),
            ],
            options={
                'verbose_name': 'Opinión de foro',
                'verbose_name_plural': 'Opiniones de foro',
            },
        ),
    ]
