# Generated by Django 4.2.25 on 2025-12-08 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion_foro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_foro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinion_actividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='opinion_actividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagen_actividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='foro',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='descripcion_actividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones', to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='curxuse',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='curxuse',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actxuse',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_por_usuario', to='cursos.actividad'),
        ),
        migrations.AddField(
            model_name='actxuse',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actxcur',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.actxcur'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.tipo_actividad'),
        ),
        migrations.AddConstraint(
            model_name='curxuse',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='unique_usuario_curso'),
        ),
        migrations.AlterUniqueTogether(
            name='actxuse',
            unique_together={('usuario', 'actividad')},
        ),
    ]
