# Generated by Django 4.2.25 on 2025-12-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion_foro',
            name='OPINION_OPINION_FORO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
