# Generated by Django 4.2.25 on 2025-12-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_opinion_foro_opinion_opinion_foro'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion_actividad',
            name='ORDEN_DESCRIPCION',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
