# Generated by Django 4.2.25 on 2025-12-08 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_CIUDAD', models.IntegerField(blank=True, null=True)),
                ('APODO', models.CharField(max_length=150)),
                ('PRIMER_NOMBRE_USUARIO', models.CharField(max_length=150)),
                ('SEGUNDO_NOMBRE_USUARIO', models.CharField(blank=True, max_length=150)),
                ('PRIMER_APELLIDO_USUARIO', models.CharField(max_length=150)),
                ('SEGUNDO_APELLIDO_USUARIO', models.CharField(blank=True, max_length=150)),
                ('TELEFONO_USUARIO', models.CharField(max_length=150)),
                ('DIRECCION_USUARIO', models.CharField(max_length=150)),
                ('FECHA_NACIMIENTO_USUARIO', models.DateField()),
                ('CORREO_USUARIO', models.EmailField(max_length=254, unique=True)),
                ('IS_STAFF', models.BooleanField(default=False)),
                ('IS_ACTIVE', models.BooleanField(default=True)),
                ('DATE_JOINED', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', general.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='AVATAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_AVATAR', models.CharField(max_length=250)),
                ('FECHA_MODIFICACION_AVATAR', models.DateField(auto_now=True)),
                ('FECHA_INGRESO_AVATAR', models.DateTimeField(auto_now_add=True)),
                ('ESTADO_AVATAR', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
            },
        ),
    ]
