# Generated by Django 4.2.25 on 2025-12-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
