# Generated by Django 4.2.25 on 2025-12-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='IS_SUPERUSER',
            field=models.BooleanField(default=False),
        ),
    ]
