# Generated by Django 4.2.25 on 2025-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWS_CREDENCIALES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AWS_ACCESS_KEY_ID', models.CharField(max_length=150)),
                ('AWS_SECRET_ACCESS_KEY', models.CharField(max_length=150)),
                ('AWS_STORAGE_BUCKET_NAME', models.CharField(max_length=150)),
                ('AWS_REGION', models.CharField(max_length=150)),
                ('IMAGEN_BASE_URL', models.CharField(max_length=150)),
                ('VIDEO_BASE_URL', models.CharField(max_length=150)),
                ('FECHA_INGRESO_AWS', models.DateTimeField(auto_now_add=True)),
                ('FECHA_MODIFICACION_AWS', models.DateField(auto_now=True)),
                ('ESTADO_AWS', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Credencial AWS',
                'verbose_name_plural': 'Credenciales AWS',
            },
        ),
        migrations.CreateModel(
            name='BOT_CREDENCIALES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRIVATE_KEY_BOT_CREDENCIAL', models.CharField(max_length=255)),
                ('NOMBRE_BOT_CREDENCIALES', models.CharField(max_length=255)),
                ('FECHA_INGRESO_BOT_CREDENCIALES', models.DateTimeField(auto_now_add=True)),
                ('FECHA_MODIFICACION_BOT_CREDENCIALES', models.DateField(auto_now=True)),
                ('ESTADO_BOT_CREDENCIALES', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Credencial de bot',
                'verbose_name_plural': 'Credenciales de bots',
            },
        ),
    ]
